spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8

logging:
  level:
    root: WARN
    de.friday: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
