spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    open-in-view: true

logging:
  level:
    root: WARN
    com.upday: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
